/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tomp.sav_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author jackt
 */
public class AdminTicket extends javax.swing.JFrame {

    private int IDD;
    /**
     * Creates new form AdminTicket
     * @param ID
     */
    public AdminTicket(int ID) {
        initComponents();
        String[] tableau;
        AdminComboProblems.setModel(new DefaultComboBoxModel<>(new String[]{
            "Choisir un type de problème", "Problème d'achat", "Problème de compte"
        }));

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppe?characterEncoding=utf8", "root", "");

            // Execute a SQL query to retrieve the data for the ComboBox
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM articles");

            // Populate the ComboBox with the data from the result set
            ArrayList<String> gameNames = new ArrayList<>();
            while (resultSet.next()) {
                String gameName = resultSet.getString("Nom");
                gameNames.add(gameName);
            }
            AdminComboConcernedGame.setModel(new DefaultComboBoxModel<>(gameNames.toArray(new String[0])));

            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        IDD = ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        LabelProblemType6 = new javax.swing.JLabel();
        LabelConcernedGame6 = new javax.swing.JLabel();
        AdminComboConcernedGame = new javax.swing.JComboBox<>();
        AdminComboProblems = new javax.swing.JComboBox<>();
        ScrollPaneDesc6 = new javax.swing.JScrollPane();
        TextAreaDesc6 = new javax.swing.JTextArea();
        LabelConcernedGame7 = new javax.swing.JLabel();
        submitTicket6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        LabelProblemType6.setText("Type de problème");

        LabelConcernedGame6.setText("Jeu concerné");
        LabelConcernedGame6.setEnabled(false);
        LabelConcernedGame6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LabelConcernedGame6ComponentHidden(evt);
            }
        });

        AdminComboConcernedGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AdminComboConcernedGame.setEnabled(false);

        AdminComboProblems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AdminComboProblems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminComboProblemsActionPerformed(evt);
            }
        });

        TextAreaDesc6.setColumns(20);
        TextAreaDesc6.setRows(5);
        ScrollPaneDesc6.setViewportView(TextAreaDesc6);

        LabelConcernedGame7.setText("Description");
        LabelConcernedGame7.setEnabled(false);
        LabelConcernedGame7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LabelConcernedGame7ComponentHidden(evt);
            }
        });

        submitTicket6.setText("Soumettre");
        submitTicket6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTicket6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelConcernedGame7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminComboConcernedGame, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminComboProblems, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelProblemType6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelConcernedGame6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScrollPaneDesc6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(submitTicket6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(LabelProblemType6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminComboProblems, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelConcernedGame6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminComboConcernedGame, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelConcernedGame7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneDesc6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitTicket6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelConcernedGame6ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LabelConcernedGame6ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelConcernedGame6ComponentHidden

    private void AdminComboProblemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminComboProblemsActionPerformed
        // TODO add your handling code here:
        String valueSelected = AdminComboProblems.getSelectedItem().toString();
        if (valueSelected.equals("Problème d'achat")) {
            AdminComboConcernedGame.setEnabled(true);
            LabelConcernedGame6.setEnabled(true);

        } else {
            AdminComboConcernedGame.setEnabled(false);
            LabelConcernedGame6.setEnabled(false);
        }
    }//GEN-LAST:event_AdminComboProblemsActionPerformed

    private void LabelConcernedGame7ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LabelConcernedGame7ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelConcernedGame7ComponentHidden

    private void submitTicket6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTicket6ActionPerformed
        String state = "Nouveau";
        String type = AdminComboProblems.getSelectedItem().toString();
        String gameName = AdminComboConcernedGame.getSelectedItem().toString();
        int gameID = 0;
        if(type.equals("Choisir un type de problème")){
            return;
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppe?characterEncoding=utf8", "root", "");

            String sql = "SELECT * FROM articles WHERE Nom = ?";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Set the value for the parameter
            statement.setString(1, gameName);

            // Execute the query
            ResultSet resultSet = statement.executeQuery();
 
            // Populate the ComboBox with the data from the result set
            while (resultSet.next()) {
                gameID = resultSet.getInt("ID_JEU");
            }
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        String description = TextAreaDesc6.getText();
        LocalDate todayDate = LocalDate.now();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppe?characterEncoding=utf8", "root", "");

            // Execute a SQL query to retrieve the data for the ComboBox
            Statement statement = connection.createStatement();
            String sql = "INSERT INTO tickets (ID, Etat, Type, ID_JEU, Description, Date) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setInt(1, IDD);
            pstmt.setString(2, state);
            pstmt.setString(3, type);
            pstmt.setInt(4, gameID);
            pstmt.setString(5, description);
            pstmt.setString(6, todayDate.toString());

            pstmt.executeUpdate();
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.dispose();

    }//GEN-LAST:event_submitTicket6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AdminComboConcernedGame;
    private javax.swing.JComboBox<String> AdminComboProblems;
    private javax.swing.JLabel LabelConcernedGame6;
    private javax.swing.JLabel LabelConcernedGame7;
    private javax.swing.JLabel LabelProblemType6;
    private javax.swing.JScrollPane ScrollPaneDesc6;
    private javax.swing.JTextArea TextAreaDesc6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton submitTicket6;
    // End of variables declaration//GEN-END:variables
}
