/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tomp.sav_project;

import java.lang.reflect.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author jackt
 */
public class NewTicket extends javax.swing.JFrame {

    /**
     * Creates new form NewTicket
     *
     * @param ID
     */
    private int IDD;

    public NewTicket(int ID) {
        initComponents();
        String[] tableau;
        ComboProblems.setModel(new DefaultComboBoxModel<>(new String[]{
            "Choisir un type de problème", "Problème d'achat", "Problème de compte"
        }));

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppe?characterEncoding=utf8", "root", "");

            // Execute a SQL query to retrieve the data for the ComboBox
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM articles");

            // Populate the ComboBox with the data from the result set
            ArrayList<String> gameNames = new ArrayList<>();
            while (resultSet.next()) {
                String gameName = resultSet.getString("Nom");
                gameNames.add(gameName);
            }
            ComboConcernedGame.setModel(new DefaultComboBoxModel<>(gameNames.toArray(new String[0])));

            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        

        IDD = ID;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboProblems = new javax.swing.JComboBox<>();
        LabelProblemType = new javax.swing.JLabel();
        ComboConcernedGame = new javax.swing.JComboBox<>();
        LabelConcernedGame = new javax.swing.JLabel();
        ScrollPaneDesc = new javax.swing.JScrollPane();
        TextAreaDesc = new javax.swing.JTextArea();
        submitTicket = new javax.swing.JButton();
        LabelConcernedGame1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ComboProblems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboProblems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProblemsActionPerformed(evt);
            }
        });

        LabelProblemType.setText("Type de problème");

        ComboConcernedGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboConcernedGame.setEnabled(false);

        LabelConcernedGame.setText("Jeu concerné");
        LabelConcernedGame.setEnabled(false);
        LabelConcernedGame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LabelConcernedGameComponentHidden(evt);
            }
        });

        TextAreaDesc.setColumns(20);
        TextAreaDesc.setRows(5);
        ScrollPaneDesc.setViewportView(TextAreaDesc);

        submitTicket.setText("Soumettre");
        submitTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTicketActionPerformed(evt);
            }
        });

        LabelConcernedGame1.setText("Description");
        LabelConcernedGame1.setEnabled(false);
        LabelConcernedGame1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LabelConcernedGame1ComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelProblemType, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScrollPaneDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelConcernedGame, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ComboConcernedGame, javax.swing.GroupLayout.Alignment.LEADING, 0, 199, Short.MAX_VALUE)
                                .addComponent(ComboProblems, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LabelConcernedGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(submitTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelProblemType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboProblems, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelConcernedGame)
                .addGap(2, 2, 2)
                .addComponent(ComboConcernedGame, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelConcernedGame1)
                .addGap(3, 3, 3)
                .addComponent(ScrollPaneDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboProblemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProblemsActionPerformed
        // TODO add your handling code here:
        String valueSelected = ComboProblems.getSelectedItem().toString();
        if (valueSelected.equals("Problème d'achat")) {
            ComboConcernedGame.setEnabled(true);
            LabelConcernedGame.setEnabled(true);

        } else {
            ComboConcernedGame.setEnabled(false);
            LabelConcernedGame.setEnabled(false);
        }
    }//GEN-LAST:event_ComboProblemsActionPerformed

    private void LabelConcernedGameComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LabelConcernedGameComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelConcernedGameComponentHidden

    private void submitTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTicketActionPerformed
        String state = "Nouveau";
        String type = ComboProblems.getSelectedItem().toString();
        String gameName = ComboConcernedGame.getSelectedItem().toString();
        int gameID = 0;
        if(type.equals("Choisir un type de problème")){
            return;
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppe?characterEncoding=utf8", "root", "");

            String sql = "SELECT * FROM articles WHERE Nom = ?";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Set the value for the parameter
            statement.setString(1, gameName);

            // Execute the query
            ResultSet resultSet = statement.executeQuery();


            // Populate the ComboBox with the data from the result set
            while (resultSet.next()) {
                gameID = resultSet.getInt("ID_JEU");
            }
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        String description = TextAreaDesc.getText();
        LocalDate todayDate = LocalDate.now();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ppe?characterEncoding=utf8", "root", "");

            // Execute a SQL query to retrieve the data for the ComboBox
            Statement statement = connection.createStatement();
            String sql = "INSERT INTO tickets (ID, Etat, Type, ID_JEU, Description, Date) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setInt(1, IDD);
            pstmt.setString(2, state);
            pstmt.setString(3, type);
            pstmt.setInt(4, gameID);
            pstmt.setString(5, description);
            pstmt.setString(6, todayDate.toString());

            pstmt.executeUpdate();
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        this.setVisible(false);
        new Client_view(IDD).setVisible(true);
               
    }//GEN-LAST:event_submitTicketActionPerformed

    private void LabelConcernedGame1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LabelConcernedGame1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelConcernedGame1ComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboConcernedGame;
    private javax.swing.JComboBox<String> ComboProblems;
    private javax.swing.JLabel LabelConcernedGame;
    private javax.swing.JLabel LabelConcernedGame1;
    private javax.swing.JLabel LabelProblemType;
    private javax.swing.JScrollPane ScrollPaneDesc;
    private javax.swing.JTextArea TextAreaDesc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitTicket;
    // End of variables declaration//GEN-END:variables
}
